package dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import pojo.Favorite;

public interface FavoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated Sat Aug 24 20:21:29 CST 2019
     */
    int deleteByPrimaryKey(Integer favoriteid);
    int deleteFavoriteByMovieId(@Param(value = "movieid") Integer movieid, @Param(value = "userid") Integer userid);
    int deleteFavoriteByTVPlayId(@Param(value = "tvplayid") Integer tvplayid,@Param(value = "userid") Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated Sat Aug 24 20:21:29 CST 2019
     */
    int insert(Favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated Sat Aug 24 20:21:29 CST 2019
     */
    Favorite selectByPrimaryKey(Integer favoriteid);

    Favorite selectByMovieId(@Param(value = "movieid") Integer movieid,@Param(value = "userid") Integer userid);
    Favorite selectByTVPlayId(@Param(value = "tvplayid") Integer tvplayid,@Param(value = "userid") Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated Sat Aug 24 20:21:29 CST 2019
     */
    List<Favorite> selectAll();
    List<Favorite> selectByUserId(Integer userid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated Sat Aug 24 20:21:29 CST 2019
     */
    int updateByPrimaryKey(Favorite record);
}