package dao;

import java.util.List;

import org.springframework.stereotype.Repository;
import pojo.MovieComment;
@Repository
public interface MovieCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviecomment
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    int deleteByPrimaryKey(Integer moviecommentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviecomment
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    int insert(MovieComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviecomment
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    MovieComment selectByPrimaryKey(Integer moviecommentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviecomment
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    List<MovieComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviecomment
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    int updateByPrimaryKey(MovieComment record);

    List<MovieComment> selectAllByMovieId(Integer movieid);

    List<MovieComment> selectAllByUserId(Integer userid);
}