package dao;

import java.util.List;

import org.springframework.stereotype.Repository;
import pojo.Movie;
@Repository
public interface MovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    int deleteByPrimaryKey(Integer movieid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    int insert(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated Mon Aug 19 15:44:57 CST 2019
     */
    Movie selectByPrimaryKey(Integer movieid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated Mon Aug 19 15:44:57 CST 2019
     */
    List<Movie> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated Mon Aug 19 15:44:57 CST 2019
     */
    int updateByPrimaryKey(Movie record);

    List<Movie> searchByLike(String name);

    List<Movie> searchByTypeLike(String type);
}