package dao;

import java.util.List;

import org.springframework.stereotype.Repository;
import pojo.TVPlayComment;
@Repository
public interface TVPlayCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tvplaycomment
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    int deleteByPrimaryKey(Integer typlaycommentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tvplaycomment
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    int insert(TVPlayComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tvplaycomment
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    TVPlayComment selectByPrimaryKey(Integer typlaycommentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tvplaycomment
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    List<TVPlayComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tvplaycomment
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    int updateByPrimaryKey(TVPlayComment record);

    List<TVPlayComment> selectAllByTVId(Integer typlayid);
}