package dao;

import java.util.List;

import org.springframework.stereotype.Repository;
import pojo.TVPlay;
@Repository
public interface TVPlayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tvplay
     *
     * @mbggenerated Mon Aug 19 19:53:04 CST 2019
     */
    int deleteByPrimaryKey(Integer tvid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tvplay
     *
     * @mbggenerated Mon Aug 19 19:53:04 CST 2019
     */
    int insert(TVPlay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tvplay
     *
     * @mbggenerated Mon Aug 19 19:53:04 CST 2019
     */
    TVPlay selectByPrimaryKey(Integer tvid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tvplay
     *
     * @mbggenerated Mon Aug 19 19:53:04 CST 2019
     */
    List<TVPlay> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tvplay
     *
     * @mbggenerated Mon Aug 19 19:53:04 CST 2019
     */
    int updateByPrimaryKey(TVPlay record);

    List<TVPlay> searchByLike(String name);
}