package dao;

import java.util.List;

import org.springframework.stereotype.Repository;
import pojo.UserInfo;
@Repository
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    int deleteByPrimaryKey(Integer userinfoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    UserInfo selectByPrimaryKey(Integer userinfoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    int updateByPrimaryKey(UserInfo record);

    UserInfo selectByUserId(Integer userid);
}