package pojo;

import org.springframework.stereotype.Component;

@Component
public class MovieComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moviecomment.movieCommentId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private Integer moviecommentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moviecomment.userId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moviecomment.movieId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private Integer movieid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moviecomment.commentTime
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private String commenttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moviecomment.commentStar
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private Integer commentstar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moviecomment.commentTitle
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private String commenttitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moviecomment.commentContent
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private String commentcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moviecomment.movieCommentId
     *
     * @return the value of moviecomment.movieCommentId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public Integer getMoviecommentid() {
        return moviecommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moviecomment.movieCommentId
     *
     * @param moviecommentid the value for moviecomment.movieCommentId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setMoviecommentid(Integer moviecommentid) {
        this.moviecommentid = moviecommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moviecomment.userId
     *
     * @return the value of moviecomment.userId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moviecomment.userId
     *
     * @param userid the value for moviecomment.userId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moviecomment.movieId
     *
     * @return the value of moviecomment.movieId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moviecomment.movieId
     *
     * @param movieid the value for moviecomment.movieId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moviecomment.commentTime
     *
     * @return the value of moviecomment.commentTime
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public String getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moviecomment.commentTime
     *
     * @param commenttime the value for moviecomment.commentTime
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setCommenttime(String commenttime) {
        this.commenttime = commenttime == null ? null : commenttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moviecomment.commentStar
     *
     * @return the value of moviecomment.commentStar
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public Integer getCommentstar() {
        return commentstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moviecomment.commentStar
     *
     * @param commentstar the value for moviecomment.commentStar
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setCommentstar(Integer commentstar) {
        this.commentstar = commentstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moviecomment.commentTitle
     *
     * @return the value of moviecomment.commentTitle
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public String getCommenttitle() {
        return commenttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moviecomment.commentTitle
     *
     * @param commenttitle the value for moviecomment.commentTitle
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setCommenttitle(String commenttitle) {
        this.commenttitle = commenttitle == null ? null : commenttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moviecomment.commentContent
     *
     * @return the value of moviecomment.commentContent
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public String getCommentcontent() {
        return commentcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moviecomment.commentContent
     *
     * @param commentcontent the value for moviecomment.commentContent
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setCommentcontent(String commentcontent) {
        this.commentcontent = commentcontent == null ? null : commentcontent.trim();
    }

    public MovieComment() {
    }

    public MovieComment(Integer userid, Integer movieid, String commenttime, Integer commentstar, String commenttitle, String commentcontent) {
        this.userid = userid;
        this.movieid = movieid;
        this.commenttime = commenttime;
        this.commentstar = commentstar;
        this.commenttitle = commenttitle;
        this.commentcontent = commentcontent;
    }
}