package pojo;

import org.springframework.stereotype.Component;

@Component
public class Movie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieId
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    private Integer movieid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieName
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    private String moviename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieCover
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    private String moviecover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieUri
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    private String movieuri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieType
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    private String movietype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieFavoriteNum
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    private Integer moviefavoritenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieStar
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    private Double moviestar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieOverview
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    private String movieoverview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieReviewId
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    private Integer moviereviewid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieCastCrewId
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    private Integer moviecastcrewid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.userId
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieId
     *
     * @return the value of movie.movieId
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieId
     *
     * @param movieid the value for movie.movieId
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieName
     *
     * @return the value of movie.movieName
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public String getMoviename() {
        return moviename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieName
     *
     * @param moviename the value for movie.movieName
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public void setMoviename(String moviename) {
        this.moviename = moviename == null ? null : moviename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieCover
     *
     * @return the value of movie.movieCover
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public String getMoviecover() {
        return moviecover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieCover
     *
     * @param moviecover the value for movie.movieCover
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public void setMoviecover(String moviecover) {
        this.moviecover = moviecover == null ? null : moviecover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieUri
     *
     * @return the value of movie.movieUri
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public String getMovieuri() {
        return movieuri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieUri
     *
     * @param movieuri the value for movie.movieUri
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public void setMovieuri(String movieuri) {
        this.movieuri = movieuri == null ? null : movieuri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieType
     *
     * @return the value of movie.movieType
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public String getMovietype() {
        return movietype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieType
     *
     * @param movietype the value for movie.movieType
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public void setMovietype(String movietype) {
        this.movietype = movietype == null ? null : movietype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieFavoriteNum
     *
     * @return the value of movie.movieFavoriteNum
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public Integer getMoviefavoritenum() {
        return moviefavoritenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieFavoriteNum
     *
     * @param moviefavoritenum the value for movie.movieFavoriteNum
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public void setMoviefavoritenum(Integer moviefavoritenum) {
        this.moviefavoritenum = moviefavoritenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieStar
     *
     * @return the value of movie.movieStar
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public Double getMoviestar() {
        return moviestar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieStar
     *
     * @param moviestar the value for movie.movieStar
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public void setMoviestar(Double moviestar) {
        this.moviestar = moviestar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieOverview
     *
     * @return the value of movie.movieOverview
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public String getMovieoverview() {
        return movieoverview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieOverview
     *
     * @param movieoverview the value for movie.movieOverview
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public void setMovieoverview(String movieoverview) {
        this.movieoverview = movieoverview == null ? null : movieoverview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieReviewId
     *
     * @return the value of movie.movieReviewId
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public Integer getMoviereviewid() {
        return moviereviewid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieReviewId
     *
     * @param moviereviewid the value for movie.movieReviewId
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public void setMoviereviewid(Integer moviereviewid) {
        this.moviereviewid = moviereviewid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieCastCrewId
     *
     * @return the value of movie.movieCastCrewId
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public Integer getMoviecastcrewid() {
        return moviecastcrewid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieCastCrewId
     *
     * @param moviecastcrewid the value for movie.movieCastCrewId
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public void setMoviecastcrewid(Integer moviecastcrewid) {
        this.moviecastcrewid = moviecastcrewid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.userId
     *
     * @return the value of movie.userId
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.userId
     *
     * @param userid the value for movie.userId
     *
     * @mbggenerated Mon Aug 19 15:44:56 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}