package pojo;

import org.springframework.stereotype.Component;

@Component
public class TVPlayComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvplaycomment.typlayCommentId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private Integer typlaycommentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvplaycomment.userId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvplaycomment.typlayId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private Integer typlayid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvplaycomment.commentTime
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private String commenttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvplaycomment.commentStar
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private Integer commentstar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvplaycomment.commentTitle
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private String commenttitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tvplaycomment.commentContent
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    private String commentcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvplaycomment.typlayCommentId
     *
     * @return the value of tvplaycomment.typlayCommentId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public Integer getTyplaycommentid() {
        return typlaycommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvplaycomment.typlayCommentId
     *
     * @param typlaycommentid the value for tvplaycomment.typlayCommentId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setTyplaycommentid(Integer typlaycommentid) {
        this.typlaycommentid = typlaycommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvplaycomment.userId
     *
     * @return the value of tvplaycomment.userId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvplaycomment.userId
     *
     * @param userid the value for tvplaycomment.userId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvplaycomment.typlayId
     *
     * @return the value of tvplaycomment.typlayId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public Integer getTyplayid() {
        return typlayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvplaycomment.typlayId
     *
     * @param typlayid the value for tvplaycomment.typlayId
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setTyplayid(Integer typlayid) {
        this.typlayid = typlayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvplaycomment.commentTime
     *
     * @return the value of tvplaycomment.commentTime
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public String getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvplaycomment.commentTime
     *
     * @param commenttime the value for tvplaycomment.commentTime
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setCommenttime(String commenttime) {
        this.commenttime = commenttime == null ? null : commenttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvplaycomment.commentStar
     *
     * @return the value of tvplaycomment.commentStar
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public Integer getCommentstar() {
        return commentstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvplaycomment.commentStar
     *
     * @param commentstar the value for tvplaycomment.commentStar
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setCommentstar(Integer commentstar) {
        this.commentstar = commentstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvplaycomment.commentTitle
     *
     * @return the value of tvplaycomment.commentTitle
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public String getCommenttitle() {
        return commenttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvplaycomment.commentTitle
     *
     * @param commenttitle the value for tvplaycomment.commentTitle
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setCommenttitle(String commenttitle) {
        this.commenttitle = commenttitle == null ? null : commenttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tvplaycomment.commentContent
     *
     * @return the value of tvplaycomment.commentContent
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public String getCommentcontent() {
        return commentcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tvplaycomment.commentContent
     *
     * @param commentcontent the value for tvplaycomment.commentContent
     *
     * @mbggenerated Thu Aug 22 14:44:02 CST 2019
     */
    public void setCommentcontent(String commentcontent) {
        this.commentcontent = commentcontent == null ? null : commentcontent.trim();
    }


    public TVPlayComment() {
    }

    public TVPlayComment(Integer userid, Integer typlayid, String commenttime, Integer commentstar, String commenttitle, String commentcontent) {
        this.userid = userid;
        this.typlayid = typlayid;
        this.commenttime = commenttime;
        this.commentstar = commentstar;
        this.commenttitle = commenttitle;
        this.commentcontent = commentcontent;
    }
}