package pojo;

import org.springframework.stereotype.Component;

@Component
public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userInfoId
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    private Integer userinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userId
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.firstName
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.lastName
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    private String lastname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.address
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.avatar
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userInfoId
     *
     * @return the value of userinfo.userInfoId
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    public Integer getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userInfoId
     *
     * @param userinfoid the value for userinfo.userInfoId
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    public void setUserinfoid(Integer userinfoid) {
        this.userinfoid = userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userId
     *
     * @return the value of userinfo.userId
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userId
     *
     * @param userid the value for userinfo.userId
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.firstName
     *
     * @return the value of userinfo.firstName
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.firstName
     *
     * @param firstname the value for userinfo.firstName
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.lastName
     *
     * @return the value of userinfo.lastName
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.lastName
     *
     * @param lastname the value for userinfo.lastName
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.address
     *
     * @return the value of userinfo.address
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.address
     *
     * @param address the value for userinfo.address
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.avatar
     *
     * @return the value of userinfo.avatar
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.avatar
     *
     * @param avatar the value for userinfo.avatar
     *
     * @mbggenerated Fri Aug 23 15:57:18 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    public UserInfo() {
    }

    public UserInfo(Integer userid, String firstname, String lastname, String address) {
        this.userid = userid;
        this.firstname = firstname;
        this.lastname = lastname;
        this.address = address;
    }
}